services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"  # Map port 8000 on the host to port 8000 in the container
    # environment:
    #   - GOOGLE_API_KEY=your_google_api_key
    #   - GROQ_API_KEY=your_groq_api_key
    #   - HUGGINGFACE_API_KEY=your_huggingface_api_key
    volumes:
      - .:/app  # Mount current directory for development (optional)
    restart: always
